[package]
name = "http-controller"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.40"
common = { path = "../common" }
form_urlencoded = "1.2.1"
serde.workspace = true
serde_json.workspace = true
wit-bindgen.workspace = true
