package platform-poc:virtual-keyvalue-batch@0.1.0;

world virtual-keyvalue-batch {
    import wasi:keyvalue/types;
    import wasi:keyvalue/readwrite;

    /// Exported read write keeps track of existing keys
    export wasi:keyvalue/readwrite;
    export wasi:keyvalue/batch;
}
