package platform-poc:products-http@0.1.0;

world products-http-service {
  // TODO
  // import wasi:keyvalue/atomic;
  // import wasi:keyvalue/batch;
  // import wasi:keyvalue/readwrite;
  // import wasi:logging/logging;

  import platform-poc:products/products@0.1.0;
  export wasi:http/incoming-handler@0.2.0-rc-2023-12-05;
}
