name = "orders-service"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "orders-service"
wasm_target = "wasm32-wasi"

[[registry.pull.sources]]
target = "platform-poc:inventory"
source = "file://../../wit/inventory"

[[registry.pull.sources]]
target = "platform-poc:orders"
source = "file://../../wit/orders"
