apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    service: order
spec:
  replicas: 1
  selector:
    matchLabels:
      service: order
  template:
    metadata:
      labels:
        service: order
    spec:
      containers:
        - name: order-service
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: platform-poc-secrets
                  key: db_url_order_service
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: platform-poc-secrets
                  key: db_usr_order_service
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-poc-secrets
                  key: db_pwd_order_service
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: platform-poc-secrets
                  key: nats_url
            - name: INVENTORY_URL
              value: "http://inventory-service.default.svc.cluster.local:8080/api/inventory"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    service: order
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 80
      protocol: TCP
  selector:
    service: order
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-service
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api/order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8081
