apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    service: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      service: notification
  template:
    metadata:
      labels:
        service: notification
    spec:
      containers:
        - name: notification-service
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: PORT
              value: "8082"
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: platform-poc-secrets
                  key: nats_url
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    service: notification
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: http
      protocol: TCP
      name: http
  selector:
    service: notification
