name = "http-hello-world"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = [
  "wasmcloud:httpserver",
  "wasmcloud:keyvalue",
  "wasmcloud:builtin:logging"
]
wit_world = "hello"
wasm_target = "wasm32-wasi-preview2"
