[package]
name = "notification-service"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid = { workspace = true, features = ["serde"] }
wit-bindgen.workspace = true
