[package]
name = "orders-service"
edition.workspace = true
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
indoc = "2.0.5"
serde.workspace = true
serde_json.workspace = true
uuid = { workspace = true, features = ["serde", "v4"] }
wit-bindgen.workspace = true
