---
version: "3.8"

services:
  postgres:
    image: postgres:16.1
    restart: always
    volumes:
      - .//database/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: '"order-service", "inventory-service"'
      POSTGRES_PASSWORD: commerce
    ports:
      - 5432:5432
