[package]
name = "order-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
dotenv = "0.15.0"
envy = "0.4.2"
serde = {version = "1.0.193", features=["derive"]}
tokio = { version = "1.35.0", features = ["full"] }
