name = "data-init"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "data-init"
wasm_target = "wasm32-wasi"

[[registry.pull.sources]]
target = "platform-poc:data-init"
source = "file://../../wit/data-init"
