apiVersion: k8s.wasmcloud.dev/v1alpha1
kind: WasmCloudHostConfig
metadata:
  name: wasmcloud-host
spec:
  lattice: default
  version: 1.5.1
  hostReplicas: 1
  allowedInsecure:
    - "host.docker.internal:5001"
