[package]
name = "products-service"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
log = "0.4.21"
serde.workspace = true
serde_json.workspace = true
uuid = { version = "1.8.0", features = ["v4"] }
wit-bindgen.workspace = true
