name = "products-service"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "products-service"
wasm_target = "wasm32-wasi"

[[registry.pull.sources]]
target = "platform-poc:products"
source = "file://../../wit/products"
