package platform-poc:http-controller;

world service {
  import wasi:logging/logging@0.1.0-draft;

  import platform-poc:products/products@0.1.0;
  import platform-poc:data-init/init-funcs@0.1.0;
  import platform-poc:inventory/inventory@0.1.0;
  import platform-poc:orders/orders@0.1.0;

  export wasi:http/incoming-handler@0.2.2;
}
