apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: inventory.yaml
secretGenerator:
  - envs:
      - .env.secret
    name: postgres-db-secrets
