apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  template:
    spec:
      containers:
        - name: order-service
          image: k3d-platform-poc.localhost:5001/platform-poc-rust/order-service:0.1.0
