[package]
name = "notification-service"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
serde.workspace = true
serde_json.workspace = true
wit-bindgen.workspace = true
