package platform-poc:inventory-service;

world inventory-service {
  import wasmcloud:postgres/query@0.1.1-draft;
  import wasi:logging/logging@0.1.0-draft;

  export platform-poc:inventory/inventory@0.1.0;
}
