apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: online-store-poc
  annotations:
    version: v0.0.1
    description: "TODO: Add a description for the application"
spec:
  components:
#################### COMPONENTS ####################
    - name: data-init
      type: component
      properties:
        image: file://../wasm-components/rust/data-init/build/data_init_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: sqldb-postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
            target_config:
              - name: default-pg
        - type: link
          properties:
            target: kvredis
            namespace: wasi
            package: keyvalue
            interfaces: [store]
            target_config:
              - name: default-redis
                properties:
                  url: redis://127.0.0.1:6379

    - name: http-controller
      type: component
      properties:
        image: file://../wasm-components/rust/http-controller/build/http_controller_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: products-service
            namespace: platform-poc
            package: products
            interfaces: [products]
        - type: link
          properties:
            target: data-init
            namespace: platform-poc
            package: data-init
            interfaces: [init-funcs]
        - type: link
          properties:
            target: inventory-service
            namespace: platform-poc
            package: inventory
            interfaces: [inventory]
        - type: link
          properties:
            target: orders-service
            namespace: platform-poc
            package: orders
            interfaces: [orders]

    - name: products-service
      type: component
      properties:
        image: file://../wasm-components/rust/products-service/build/products_service_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: kvredis
            namespace: wasi
            package: keyvalue
            interfaces: [store]
            target_config:
              - name: default-redis
                properties:
                  url: redis://127.0.0.1:6379

    - name: inventory-service
      type: component
      properties:
        image: file://../wasm-components/rust/inventory-service/build/inventory_service_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: sqldb-postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
            target_config:
              - name: default-pg

    - name: notification-service
      type: component
      properties:
        image: file://../wasm-components/rust/notification-service/build/notification_service_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1

    - name: orders-service
      type: component
      properties:
        image: file://../wasm-components/rust/orders-service/build/orders_service_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: sqldb-postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
            target_config:
              - name: default-pg
        - type: link
          properties:
            target: inventory-service
            namespace: platform-poc
            package: inventory
            interfaces: [inventory]
        - type: link
          properties:
            target: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

#################### CAPABILITIES ####################

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.20.0
      traits:
        - type: link
          properties:
            target: http-controller
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080

    - name: kvredis
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-redis:0.24.0

    - name: sqldb-postgres
      type: capability
      properties:
        image: ghcr.io/wasmcloud/sqldb-postgres:0.1.0

    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.20.0
      traits:
        - type: link
          properties:
            target: notification-service
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source_config:
              - name: default-nats
                properties:
                  subscriptions: "platform-poc.order-notification"        