apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: online-store-poc
  annotations:
    version: v0.0.1
    description: "TODO: Add a description for the application"
spec:
  components:
    #################### COMPONENTS ####################
    - name: data-init
      type: component
      properties:
        image: file://signed/data_init_s.wasm
        id: data-init
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: sqldb-postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
            target_config:
              - name: online_store_poc-default_pg
        - type: link
          properties:
            target: kv-redis
            namespace: wasi
            package: keyvalue
            interfaces: [store]
            target_config:
              - name: online_store_poc-default_redis

    - name: http-controller
      type: component
      properties:
        image: file://signed/http_controller_s.wasm
        id: http-controller
      traits:
        - type: spreadscaler
          properties:
            instances: 20
        - type: link
          properties:
            target: products-service
            namespace: platform-poc
            package: products
            interfaces: [products]
        - type: link
          properties:
            target: data-init
            namespace: platform-poc
            package: data-init
            interfaces: [init-funcs]
        - type: link
          properties:
            target: inventory-service
            namespace: platform-poc
            package: inventory
            interfaces: [inventory]
        - type: link
          properties:
            target: orders-service
            namespace: platform-poc
            package: orders
            interfaces: [orders]

    - name: products-service
      type: component
      properties:
        image: file://signed/products_service_s.wasm
        id: products-service
      traits:
        - type: spreadscaler
          properties:
            instances: 20
        - type: link
          properties:
            target: kv-redis
            namespace: wasi
            package: keyvalue
            interfaces: [store]
            target_config:
              - name: online_store_poc-default_redis

    - name: inventory-service
      type: component
      properties:
        image: file://signed/inventory_service_s.wasm
        id: inventory-service
      traits:
        - type: spreadscaler
          properties:
            instances: 20
        - type: link
          properties:
            target: sqldb-postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
            target_config:
              - name: online_store_poc-default_pg

    - name: notification-service
      type: component
      properties:
        image: file://signed/notification_service_s.wasm
        id: notification-service
      traits:
        - type: spreadscaler
          properties:
            instances: 20

    - name: orders-service
      type: component
      properties:
        image: file://signed/orders_service_s.wasm
        id: orders-service
      traits:
        - type: spreadscaler
          properties:
            instances: 20
        - type: link
          properties:
            target: sqldb-postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
            target_config:
              - name: online_store_poc-default_pg
        - type: link
          properties:
            target: inventory-service
            namespace: platform-poc
            package: inventory
            interfaces: [inventory]
        - type: link
          properties:
            target: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    #################### CAPABILITIES ####################

    - name: http-server
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
        id: http-server
      traits:
        - type: link
          properties:
            name: http-server
            target: http-controller
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  port: "8080"

    - name: kv-redis
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-redis:0.27.0
        id: kv-redis
        config:
          - name: default-redis
            properties:
              url: "redis://127.0.0.1:6379"

    - name: sqldb-postgres
      type: capability
      properties:
        image: ghcr.io/wasmcloud/sqldb-postgres:0.2.0
        # this one also works ...
        # image: ghcr.io/wasmcloud/sqldb-postgres:877830d
        # but 0.3.0 is broken. Have pinged Victor Adossi at Cosmonic in slack
        id: sqldb-postgres
        config:
          - name: default-pg
            properties:
              POSTGRES_HOST: localhost
              POSTGRES_PORT: "5432"
              POSTGRES_USERNAME: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_TLS_REQUIRED: "false"
              POSTGRES_DATABASE: postgres

    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.22.0
        id: nats
      traits:
        - type: link
          properties:
            target: notification-service
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source_config:
              - name: default-nats
                properties:
                  subscriptions: "platform-poc.order-notification"
