--
-- PostgreSQL database dump
--
-- Dumped from database version 16.1 (Debian 16.1-1.pgdg120+1)
-- Dumped by pg_dump version 16.1 (Homebrew)
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
-- SELECT pg_catalog.set_config('search_path', '', false);
SET search_path TO DEFAULT;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;
--
-- Name: t_order_line_items; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.t_order_line_items (
id bigint NOT NULL,
price numeric(19, 2),
quantity integer,
sku_code character varying(255)
);
--
-- Name: t_order_line_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE
public.t_order_line_items
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_order_line_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  );
--
-- Name: t_orders; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.t_orders (
id bigint NOT NULL,
order_number character varying(255)
);
--
-- Name: t_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE
public.t_orders
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_orders_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
  );
--
-- Name: t_orders_order_line_items_list; Type: TABLE; Schema: public; Owner: postgres
--
CREATE TABLE public.t_orders_order_line_items_list (
order_id bigint NOT NULL,
order_line_items_list_id bigint NOT NULL
);
--
-- Name: t_order_line_items t_order_line_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE
ONLY public.t_order_line_items
ADD CONSTRAINT t_order_line_items_pkey PRIMARY KEY (id);
--
-- Name: t_orders t_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE
ONLY public.t_orders
ADD CONSTRAINT t_orders_pkey PRIMARY KEY (id);
--
-- Name: t_orders_order_line_items_list uk_nqpoocsk2utvq7va8bgth1mj9; Type: CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE
ONLY public.t_orders_order_line_items_list
ADD CONSTRAINT uk_nqpoocsk2utvq7va8bgth1mj9 UNIQUE (order_line_items_list_id);
--
-- Name: t_orders_order_line_items_list fk1qq155yd0omg8y9in6526bhaj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE
ONLY public.t_orders_order_line_items_list
ADD CONSTRAINT fk1qq155yd0omg8y9in6526bhaj FOREIGN KEY (order_line_items_list_id) REFERENCES public.t_order_line_items(id);
--
-- Name: t_orders_order_line_items_list fk3wdgw7hxmodjqfulfaymc8aof; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
ALTER TABLE
ONLY public.t_orders_order_line_items_list
ADD CONSTRAINT fk3wdgw7hxmodjqfulfaymc8aof FOREIGN KEY (order_id) REFERENCES public.t_orders(id);
--
-- PostgreSQL database dump complete
--
