apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: inventory.yaml
  - path: notification.yaml
  - path: order.yaml
  - path: product.yaml
secretGenerator:
  - envs:
      - .env.secret
    name: platform-poc-secrets
