apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  template:
    spec:
      containers:
        - name: product-service
          image: k3d-platform-poc.localhost:5001/platform-poc-java/product-service:0.1.0
