[workspace]
members = [
    "common",
    "data-init",
    "http-controller",
    "inventory-service",
    "notification-service",
    "orders-service",
    "products-service",
]
resolver = "2"

[workspace.dependencies]
serde_json = "1.0.117"
serde = { version = "1.0", features = ["derive"] }
wit-bindgen = "0.29"
