package platform-poc:keyvalue@0.1.0;

interface types {
    resource bucket {
        open: static func(name: string) -> result<bucket, error>;
    }

    type key = string;
    type value = list<u8>;
    type key-value = tuple<key, value>;

    variant error {
        internal(string),
    }
}

interface keyvalue {
    use types.{bucket, error, key, key-value, value };

    /// Gets all known keys
    get-all: func(bucket: bucket) -> result<list<key-value>, error>;

    /// Set a key to value
    set: func(bucket: bucket, key: key, value: value) -> result<_, error>;
}
